
[
    
    {
        id:1,
        firstName:"sabelo",
        position:"CEO",
        empNum:1230002,
        manager:"565",
        children:[123,132,4242]
    },
    {
        id:2,
        firstName:"lindo",
        position:"pos2",
        empNum:123,
        manager:1230002,
        children:[987,165]
    },
    {
        id:3,
        firstName:"Ntokozo",
        position:"pos3",
        empNum:132,
        manager:1230002,
        children:[2356]
    },
    {
        id:4,
        firstName:"Zanele",
        position:"pos4",
        empNum:4242,
        manager:1230002,
        children:[]
    },
    {
        id:5,
        firstName:"Natasha",
        position:"pos5",
        empNum:987,
        manager:123,
        children:[]
    },
    {
        id:6,
        firstName:"Mandla",
        position:"pos5",
        empNum:165,
        manager:123,
        children:[]
    },
    {
        id:7,
        firstName:"Lungisa",
        position:"pos7",
        empNum:2356,
        manager:132,
        children:[6599]
    },
    {
        id:8,
        firstName:"Luyanda",
        position:"pos8",
        empNum:6599,
        manager:2356,
        children:[]
    },
    
]